/* Generated by re2c 1.1.1 on Mon Aug  5 10:54:32 2019 */
#line 1 "re2c/base64_checker.re"
#include <stdio.h>
#include "dynamic_strings.h"

#define YYMAXFILL 1


int base64_string(const char *base64_str)
{
	const char *YYCURSOR = base64_str;
	loop:
    
    
#line 16 "src/base64_checker.c"
{
	char yych;
	yych = *YYCURSOR;
	switch (yych) {
	case 0x00:	goto yy2;
	case '\n':
	case ' ':
	case '+':
	case '/':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case '=':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':	goto yy6;
	default:	goto yy4;
	}
yy2:
	++YYCURSOR;
#line 19 "re2c/base64_checker.re"
	{ return 1; }
#line 94 "src/base64_checker.c"
yy4:
	++YYCURSOR;
#line 18 "re2c/base64_checker.re"
	{ return 0; }
#line 99 "src/base64_checker.c"
yy6:
	++YYCURSOR;
#line 20 "re2c/base64_checker.re"
	{ goto loop; }
#line 104 "src/base64_checker.c"
}
#line 21 "re2c/base64_checker.re"

}
