/* Generated by re2c 1.3 on Sun Apr 19 02:30:33 2020 */
#line 1 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
#define _POSIX_C_SOURCE 200809L
#include <stdio.h>
#include <stdint.h>
#include <string.h>
#include <assert.h>
#include <string.h>
#include <memory.h>
#include <malloc.h>
#include "minijson.h"

//TODO: Full support standart https://tools.ietf.org/html/rfc8259

#define MINIJSON_RECURSION_LIMIT 10000 // i think this better then nothing ?

#define YYGETLEN(x1, x2) (size_t)(x2 - x1)

#define YYDBG() printf("FUNCTION %s ERROR : %.*s\n",__FUNCTION__, (int)(input->YYLIMIT - input->YYCURSOR), input->YYCURSOR)
#define YYDEBUG(s, c) printf("function: %s state: %d char: %c\n", __FUNCTION__, s, c)

#define YYLINKLIST new_item = minijson_new_item(); \
if (new_item == NULL) { goto error; } \
if (head == NULL) { current_item = head = new_item; } else { current_item->next = new_item; new_item->prev = current_item; current_item = new_item; }

typedef struct
{
	uint8_t *YYCURSOR;
	uint8_t *YYMARKER;
	uint8_t *YYCTXMARKER;
	uint8_t *YYLIMIT;
	uint8_t *PTR;
	int recursion_level;
} parser_input_t;

// re2 >= 1.2
// re2c re2c/minijson_tokeinizer.re2c -8 --input-encoding utf8 --tags -o minijson.c

#define YYMAXFILL 6


#line 77 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"


static char *minijson_alloc_string(uint8_t *t1, uint8_t *t2)
{
		size_t size = (size_t)(t2 - t1);
		char *ptr = (char*)malloc(size + 1);
		strncpy(ptr, (char*)(t1), size);

		ptr[size] = '\0';
		return ptr;
}

static minijson *minijson_new_item(void)
{
	minijson *ptr = (minijson*)calloc(1, sizeof(minijson));
	return ptr;
}

static char *minijson_parse_string(uint8_t *t1, uint8_t *t2)
{
	parser_input_t input;
	memset(&input, 0, sizeof(input));

	#line 107 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"


	size_t len = (size_t)(t2 - t1);
	size_t len_new = 0;
}

static bool minijson_parse_array(parser_input_t *input, minijson *item);
static bool minijson_parse_object(parser_input_t *input, minijson *item);
static bool minijson_parse_value(parser_input_t *input, minijson *item);

static bool minijson_parse_array(parser_input_t *input, minijson *item)
{
assert(input);
assert(item);

bool item_parsed = false;
bool sep = false;
minijson *head = NULL; /* head of the linked list */
minijson *current_item = NULL;
minijson *new_item = NULL;

input->recursion_level--;
if(input->recursion_level == 0) goto error;
assert(input->recursion_level >= 0);

uint8_t *t1, *t2, *t3, *t4;
uint8_t *yyt1;uint8_t *yyt2;

loop:

#line 98 "src/minijson.c"
{
	uint8_t yych;
	unsigned int yyaccept = 0;
	yych = *input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	case '"':	goto yy7;
	case ',':	goto yy8;
	case '-':
		yyt1 = input->YYCURSOR;
		goto yy10;
	case '0':
		yyt1 = input->YYCURSOR;
		goto yy11;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = input->YYCURSOR;
		goto yy13;
	case '[':	goto yy15;
	case ']':	goto yy17;
	case 'f':	goto yy19;
	case 'n':	goto yy20;
	case 't':	goto yy21;
	case '{':	goto yy22;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yyeof;
		}
		goto yy2;
	}
yy2:
	++input->YYCURSOR;
yy3:
#line 166 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto error; }
#line 144 "src/minijson.c"
yy4:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy4;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy6;
	}
yy6:
#line 145 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto loop; }
#line 160 "src/minijson.c"
yy7:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case '\v':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yy3;
		}
		yyt1 = input->YYCURSOR;
		goto yy24;
	case '"':
		yyt1 = input->YYCURSOR;
		goto yy27;
	case '\\':
		yyt1 = input->YYCURSOR;
		goto yy29;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:
		yyt1 = input->YYCURSOR;
		goto yy30;
	case 0xE0:
		yyt1 = input->YYCURSOR;
		goto yy31;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:
		yyt1 = input->YYCURSOR;
		goto yy32;
	case 0xF0:
		yyt1 = input->YYCURSOR;
		goto yy33;
	case 0xF1:
	case 0xF2:
	case 0xF3:
		yyt1 = input->YYCURSOR;
		goto yy34;
	case 0xF4:
		yyt1 = input->YYCURSOR;
		goto yy35;
	default:	goto yy3;
	}
yy8:
	++input->YYCURSOR;
#line 147 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(sep == false) { sep = true; goto loop; } else goto error; }
#line 365 "src/minijson.c"
yy10:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':	goto yy11;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy3;
	}
yy11:
	yyaccept = 1;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '.':	goto yy36;
	case 'E':
	case 'e':	goto yy37;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy12;
	}
yy12:
	t1 = yyt1;
	t2 = input->YYCURSOR;
#line 157 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_NUMBER; item->valueint = atoi(t1); goto loop; }
#line 401 "src/minijson.c"
yy13:
	yyaccept = 1;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '.':	goto yy36;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy13;
	case 'E':
	case 'e':	goto yy37;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy12;
	}
yy15:
	yyaccept = 2;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy38;
	case ']':	goto yy40;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy16;
	}
yy16:
#line 154 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST if(!minijson_parse_array(input, current_item)) { goto error; } else { goto loop; } }
#line 441 "src/minijson.c"
yy17:
	++input->YYCURSOR;
#line 148 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(sep == true) { goto error; } goto end; }
#line 446 "src/minijson.c"
yy19:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 'a':	goto yy42;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy3;
	}
yy20:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 'u':	goto yy43;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy3;
	}
yy21:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 'r':	goto yy44;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy3;
	}
yy22:
	yyaccept = 3;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy45;
	case '}':	goto yy47;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy23;
	}
yy23:
#line 151 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST if(!minijson_parse_object(input, current_item)) { goto error; } else { goto loop; } }
#line 494 "src/minijson.c"
yy24:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case '\v':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yy26;
		}
		goto yy24;
	case '"':	goto yy27;
	case '\\':	goto yy29;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy30;
	case 0xE0:	goto yy31;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy32;
	case 0xF0:	goto yy33;
	case 0xF1:
	case 0xF2:
	case 0xF3:	goto yy34;
	case 0xF4:	goto yy35;
	default:	goto yy26;
	}
yy26:
	input->YYCURSOR = input->YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy3;
	case 1: 	goto yy12;
	case 2: 	goto yy16;
	case 3: 	goto yy23;
	default:	goto yy52;
	}
yy27:
	++input->YYCURSOR;
	t1 = yyt1;
	t2 = input->YYCURSOR - 1;
#line 164 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; YYLINKLIST current_item->valuestring = minijson_alloc_string(t1, t2); current_item->type = MINI_JSON_STRING; goto loop; }
#line 692 "src/minijson.c"
yy29:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '"':
	case '/':
	case '\\':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':	goto yy24;
	case 'u':	goto yy49;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy30:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy24;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy31:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy30;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy32:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy30;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy33:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy32;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy34:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy32;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy35:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:	goto yy32;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy36:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy50;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy37:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy53;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy54;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy38:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy38;
	case ']':	goto yy40;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy40:
	++input->YYCURSOR;
#line 153 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_ARRAY; goto loop; }
#line 1101 "src/minijson.c"
yy42:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'l':	goto yy56;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy43:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'l':	goto yy57;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy44:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'u':	goto yy58;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy45:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy45;
	case '}':	goto yy47;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy47:
	++input->YYCURSOR;
#line 150 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_OBJECT; goto loop; }
#line 1146 "src/minijson.c"
yy49:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy24;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy50:
	yyaccept = 4;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy50;
	case 'E':
	case 'e':	goto yy37;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy52;
	}
yy52:
	t1 = yyt1;
	t2 = input->YYCURSOR;
#line 156 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_NUMBER; item->valuedouble = atof(t1); goto loop; }
#line 1203 "src/minijson.c"
yy53:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy54;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy54:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy54;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy52;
	}
yy56:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 's':	goto yy59;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy57:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'l':	goto yy60;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy58:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'e':	goto yy62;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy59:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'e':	goto yy64;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy26;
	}
yy60:
	++input->YYCURSOR;
#line 162 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_NULL; goto loop; }
#line 1280 "src/minijson.c"
yy62:
	++input->YYCURSOR;
#line 160 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_BOOL; current_item->valuebool = true; goto loop; }
#line 1285 "src/minijson.c"
yy64:
	++input->YYCURSOR;
#line 159 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if( (sep == false && item_parsed == true) || (sep == true && item_parsed == false) ) goto error; sep = false; item_parsed = true; if(current_item == NULL || current_item->string == NULL) YYLINKLIST current_item->type = MINI_JSON_BOOL; current_item->valuebool = false; goto loop; }
#line 1290 "src/minijson.c"
yyeof:
#line 144 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto error; }
#line 1294 "src/minijson.c"
}
#line 167 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"


error:
YYDBG();
if(head) minijson_delete(head);
return false;

end:
input->recursion_level++;

item->type = MINI_JSON_ARRAY;
item->child = head;

return true;
}

static bool minijson_parse_object(parser_input_t *input, minijson *item)
{
assert(input);
assert(item);

bool item_parsed = false;
bool sep = false;
bool colon = false;
minijson *head = NULL; /* head of the linked list */
minijson *current_item = NULL;
minijson *new_item = NULL;

input->recursion_level--;
if(input->recursion_level == 0) goto error;
assert(input->recursion_level >= 0);

uint8_t *t1, *t2, *t3, *t4;
uint8_t *yyt1;uint8_t *yyt2;
loop:

#line 1333 "src/minijson.c"
{
	uint8_t yych;
	yych = *input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy70;
	case '"':	goto yy73;
	case ',':	goto yy74;
	case '}':	goto yy76;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yyeof;
		}
		goto yy68;
	}
yy68:
	++input->YYCURSOR;
yy69:
#line 218 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto error; }
#line 1356 "src/minijson.c"
yy70:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy70;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy72;
	}
yy72:
#line 211 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto loop; }
#line 1372 "src/minijson.c"
yy73:
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case '\v':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yy69;
		}
		yyt1 = input->YYCURSOR;
		goto yy78;
	case '"':
		yyt1 = yyt2 = input->YYCURSOR;
		goto yy81;
	case '\\':
		yyt1 = input->YYCURSOR;
		goto yy83;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:
		yyt1 = input->YYCURSOR;
		goto yy84;
	case 0xE0:
		yyt1 = input->YYCURSOR;
		goto yy85;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:
		yyt1 = input->YYCURSOR;
		goto yy86;
	case 0xF0:
		yyt1 = input->YYCURSOR;
		goto yy87;
	case 0xF1:
	case 0xF2:
	case 0xF3:
		yyt1 = input->YYCURSOR;
		goto yy88;
	case 0xF4:
		yyt1 = input->YYCURSOR;
		goto yy89;
	default:	goto yy69;
	}
yy74:
	++input->YYCURSOR;
#line 213 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(sep == false) { sep = true; goto loop; } else { goto error; } }
#line 1576 "src/minijson.c"
yy76:
	++input->YYCURSOR;
#line 214 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(sep == true) { goto error; } else { goto end; } }
#line 1581 "src/minijson.c"
yy78:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case '\v':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yy80;
		}
		goto yy78;
	case '"':
		yyt2 = input->YYCURSOR;
		goto yy81;
	case '\\':	goto yy83;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy84;
	case 0xE0:	goto yy85;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy86;
	case 0xF0:	goto yy87;
	case 0xF1:
	case 0xF2:
	case 0xF3:	goto yy88;
	case 0xF4:	goto yy89;
	default:	goto yy80;
	}
yy80:
	input->YYCURSOR = input->YYMARKER;
	goto yy69;
yy81:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy81;
	case ':':	goto yy90;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy83:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '"':
	case '/':
	case '\\':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':	goto yy78;
	case 'u':	goto yy93;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy84:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy78;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy85:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy84;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy86:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy84;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy87:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy86;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy88:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy86;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy89:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:	goto yy86;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yy90:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy90;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy92;
	}
yy92:
	t1 = yyt1;
	t2 = yyt2;
#line 216 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(sep == true && item_parsed == false) goto error; sep = false; item_parsed = true; YYLINKLIST current_item->string = minijson_alloc_string(t1, t2); if(!minijson_parse_value(input, current_item)) { goto error; } else { goto loop; } }
#line 2152 "src/minijson.c"
yy93:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy78;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy80;
	}
yyeof:
#line 210 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto error; }
#line 2186 "src/minijson.c"
}
#line 219 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"


error:
YYDBG();
if(head) minijson_delete(head);
return false;

end:
input->recursion_level++;

item->type = MINI_JSON_OBJECT;
item->child = head;

return true;
}

static bool minijson_parse_value(parser_input_t *input, minijson *item)
{
assert(input);
assert(item);
uint8_t *t1, *t2, *t3, *t4;
uint8_t *yyt1;uint8_t *yyt2;

loop:

#line 2214 "src/minijson.c"
{
	uint8_t yych;
	unsigned int yyaccept = 0;
	yych = *input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy98;
	case '"':	goto yy101;
	case '-':
		yyt1 = input->YYCURSOR;
		goto yy102;
	case '0':
		yyt1 = input->YYCURSOR;
		goto yy103;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
		yyt1 = input->YYCURSOR;
		goto yy105;
	case '[':	goto yy107;
	case 'f':	goto yy109;
	case 'n':	goto yy110;
	case 't':	goto yy111;
	case '{':	goto yy112;
	case 0xC3:	goto yy114;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yyeof;
		}
		goto yy96;
	}
yy96:
	++input->YYCURSOR;
yy97:
#line 271 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto error; }
#line 2259 "src/minijson.c"
yy98:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy98;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy100;
	}
yy100:
#line 253 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto loop; }
#line 2275 "src/minijson.c"
yy101:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case '\v':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yy97;
		}
		yyt1 = input->YYCURSOR;
		goto yy115;
	case '"':
		yyt1 = input->YYCURSOR;
		goto yy118;
	case '\\':
		yyt1 = input->YYCURSOR;
		goto yy120;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:
		yyt1 = input->YYCURSOR;
		goto yy121;
	case 0xE0:
		yyt1 = input->YYCURSOR;
		goto yy122;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:
		yyt1 = input->YYCURSOR;
		goto yy123;
	case 0xF0:
		yyt1 = input->YYCURSOR;
		goto yy124;
	case 0xF1:
	case 0xF2:
	case 0xF3:
		yyt1 = input->YYCURSOR;
		goto yy125;
	case 0xF4:
		yyt1 = input->YYCURSOR;
		goto yy126;
	default:	goto yy97;
	}
yy102:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':	goto yy103;
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy97;
	}
yy103:
	yyaccept = 1;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '.':	goto yy127;
	case 'E':
	case 'e':	goto yy128;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy104;
	}
yy104:
	t1 = yyt1;
	t2 = input->YYCURSOR;
#line 262 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_NUMBER; item->valueint = atoi(t1); goto end; }
#line 2511 "src/minijson.c"
yy105:
	yyaccept = 1;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '.':	goto yy127;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy105;
	case 'E':
	case 'e':	goto yy128;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy104;
	}
yy107:
	yyaccept = 2;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy129;
	case ']':	goto yy131;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy108;
	}
yy108:
#line 259 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(!minijson_parse_array(input, item)) { goto error; } else { goto end; } }
#line 2551 "src/minijson.c"
yy109:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 'a':	goto yy133;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy97;
	}
yy110:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 'u':	goto yy134;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy97;
	}
yy111:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 'r':	goto yy135;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy97;
	}
yy112:
	yyaccept = 3;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy136;
	case '}':	goto yy138;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy113;
	}
yy113:
#line 256 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(!minijson_parse_object(input, item)) { goto error; } else { goto end; } }
#line 2599 "src/minijson.c"
yy114:
	yyaccept = 0;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case 0xAF:	goto yy140;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy97;
	}
yy115:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x00:
	case 0x01:
	case 0x02:
	case 0x03:
	case 0x04:
	case 0x05:
	case 0x06:
	case 0x07:
	case '\v':
	case 0x0E:
	case 0x0F:
	case 0x10:
	case 0x11:
	case 0x12:
	case 0x13:
	case 0x14:
	case 0x15:
	case 0x16:
	case 0x17:
	case 0x18:
	case 0x19:
	case 0x1A:
	case 0x1B:
	case 0x1C:
	case 0x1D:
	case 0x1E:
	case 0x1F:
	case ' ':
	case '!':
	case '#':
	case '$':
	case '%':
	case '&':
	case '\'':
	case '(':
	case ')':
	case '*':
	case '+':
	case ',':
	case '-':
	case '.':
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case ':':
	case ';':
	case '<':
	case '=':
	case '>':
	case '?':
	case '@':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'G':
	case 'H':
	case 'I':
	case 'J':
	case 'K':
	case 'L':
	case 'M':
	case 'N':
	case 'O':
	case 'P':
	case 'Q':
	case 'R':
	case 'S':
	case 'T':
	case 'U':
	case 'V':
	case 'W':
	case 'X':
	case 'Y':
	case 'Z':
	case '[':
	case ']':
	case '^':
	case '_':
	case '`':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':
	case 'g':
	case 'h':
	case 'i':
	case 'j':
	case 'k':
	case 'l':
	case 'm':
	case 'n':
	case 'o':
	case 'p':
	case 'q':
	case 'r':
	case 's':
	case 't':
	case 'u':
	case 'v':
	case 'w':
	case 'x':
	case 'y':
	case 'z':
	case '{':
	case '|':
	case '}':
	case '~':
	case 0x7F:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yy117;
		}
		goto yy115;
	case '"':	goto yy118;
	case '\\':	goto yy120;
	case 0xC2:
	case 0xC3:
	case 0xC4:
	case 0xC5:
	case 0xC6:
	case 0xC7:
	case 0xC8:
	case 0xC9:
	case 0xCA:
	case 0xCB:
	case 0xCC:
	case 0xCD:
	case 0xCE:
	case 0xCF:
	case 0xD0:
	case 0xD1:
	case 0xD2:
	case 0xD3:
	case 0xD4:
	case 0xD5:
	case 0xD6:
	case 0xD7:
	case 0xD8:
	case 0xD9:
	case 0xDA:
	case 0xDB:
	case 0xDC:
	case 0xDD:
	case 0xDE:
	case 0xDF:	goto yy121;
	case 0xE0:	goto yy122;
	case 0xE1:
	case 0xE2:
	case 0xE3:
	case 0xE4:
	case 0xE5:
	case 0xE6:
	case 0xE7:
	case 0xE8:
	case 0xE9:
	case 0xEA:
	case 0xEB:
	case 0xEC:
	case 0xED:
	case 0xEE:
	case 0xEF:	goto yy123;
	case 0xF0:	goto yy124;
	case 0xF1:
	case 0xF2:
	case 0xF3:	goto yy125;
	case 0xF4:	goto yy126;
	default:	goto yy117;
	}
yy117:
	input->YYCURSOR = input->YYMARKER;
	switch (yyaccept) {
	case 0: 	goto yy97;
	case 1: 	goto yy104;
	case 2: 	goto yy108;
	case 3: 	goto yy113;
	default:	goto yy144;
	}
yy118:
	++input->YYCURSOR;
	t1 = yyt1;
	t2 = input->YYCURSOR - 1;
#line 269 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->valuestring = minijson_alloc_string(t1, t2); item->type = MINI_JSON_STRING; goto end; }
#line 2807 "src/minijson.c"
yy120:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '"':
	case '/':
	case '\\':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':	goto yy115;
	case 'u':	goto yy141;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy121:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy115;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy122:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy121;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy123:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy121;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy124:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy123;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy125:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:
	case 0x90:
	case 0x91:
	case 0x92:
	case 0x93:
	case 0x94:
	case 0x95:
	case 0x96:
	case 0x97:
	case 0x98:
	case 0x99:
	case 0x9A:
	case 0x9B:
	case 0x9C:
	case 0x9D:
	case 0x9E:
	case 0x9F:
	case 0xA0:
	case 0xA1:
	case 0xA2:
	case 0xA3:
	case 0xA4:
	case 0xA5:
	case 0xA6:
	case 0xA7:
	case 0xA8:
	case 0xA9:
	case 0xAA:
	case 0xAB:
	case 0xAC:
	case 0xAD:
	case 0xAE:
	case 0xAF:
	case 0xB0:
	case 0xB1:
	case 0xB2:
	case 0xB3:
	case 0xB4:
	case 0xB5:
	case 0xB6:
	case 0xB7:
	case 0xB8:
	case 0xB9:
	case 0xBA:
	case 0xBB:
	case 0xBC:
	case 0xBD:
	case 0xBE:
	case 0xBF:	goto yy123;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy126:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0x80:
	case 0x81:
	case 0x82:
	case 0x83:
	case 0x84:
	case 0x85:
	case 0x86:
	case 0x87:
	case 0x88:
	case 0x89:
	case 0x8A:
	case 0x8B:
	case 0x8C:
	case 0x8D:
	case 0x8E:
	case 0x8F:	goto yy123;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy127:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy142;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy128:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '+':
	case '-':	goto yy145;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy146;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy129:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy129;
	case ']':	goto yy131;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy131:
	++input->YYCURSOR;
#line 258 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_ARRAY; goto end; }
#line 3216 "src/minijson.c"
yy133:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'l':	goto yy148;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy134:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'l':	goto yy149;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy135:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'u':	goto yy150;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy136:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy136;
	case '}':	goto yy138;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy138:
	++input->YYCURSOR;
#line 255 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_OBJECT; goto end; }
#line 3261 "src/minijson.c"
yy140:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xC2:	goto yy151;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy141:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy115;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy142:
	yyaccept = 4;
	yych = *(input->YYMARKER = ++input->YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy142;
	case 'E':
	case 'e':	goto yy128;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy144;
	}
yy144:
	t1 = yyt1;
	t2 = input->YYCURSOR;
#line 261 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_NUMBER; item->valuedouble = atof(t1); goto end; }
#line 3327 "src/minijson.c"
yy145:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy146;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy146:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy146;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy144;
	}
yy148:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 's':	goto yy152;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy149:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'l':	goto yy153;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy150:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'e':	goto yy155;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy151:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xBB:	goto yy157;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy152:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 'e':	goto yy158;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy153:
	++input->YYCURSOR;
#line 267 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_NULL; goto end; }
#line 3413 "src/minijson.c"
yy155:
	++input->YYCURSOR;
#line 265 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_BOOL; item->valuebool = true; goto end; }
#line 3418 "src/minijson.c"
yy157:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xC2:	goto yy160;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy158:
	++input->YYCURSOR;
#line 264 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ item->type = MINI_JSON_BOOL; item->valuebool = false; goto end; }
#line 3432 "src/minijson.c"
yy160:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case 0xBF:	goto yy161;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy117;
	}
yy161:
	++input->YYCURSOR;
#line 252 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto loop; }
#line 3446 "src/minijson.c"
yyeof:
#line 251 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto error; }
#line 3450 "src/minijson.c"
}
#line 272 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"


error:
YYDBG();
return false;

end:
return true;
}

// good = true
// bad = false
static bool minijson_check_string(parser_input_t *input)
{
assert(input);

loop:

#line 3471 "src/minijson.c"
{
	uint8_t yych;
	yych = *input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy167;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
			goto yyeof;
		}
		goto yy165;
	}
yy165:
	++input->YYCURSOR;
yy166:
#line 299 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto bad; }
#line 3491 "src/minijson.c"
yy167:
	yych = *++input->YYCURSOR;
	switch (yych) {
	case '\t':
	case '\n':
	case '\r':
	case ' ':	goto yy167;
	default:
		if (input->YYLIMIT <= input->YYCURSOR) {
		}
		goto yy169;
	}
yy169:
#line 298 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ goto loop; }
#line 3507 "src/minijson.c"
yyeof:
#line 297 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"
	{ if(input->YYCURSOR == input->YYLIMIT) goto ok; else goto bad; }
#line 3511 "src/minijson.c"
}
#line 300 "/home/mr0maks/minijson/re2c/minijson_tokeinizer.re2c"


ok:
return true;
bad:
return false;
}

minijson *minijson_parse(const char *string)
{
	assert(string);

	parser_input_t *input = (parser_input_t*)malloc(sizeof(parser_input_t));
	memset(input, 0, sizeof(*input));

	input->YYCURSOR = (uint8_t*)string;
	input->YYLIMIT = (uint8_t*)(string + strlen(string));
	input->PTR = (uint8_t*)string;
	input->recursion_level = MINIJSON_RECURSION_LIMIT;

	minijson *main = minijson_new_item();

	bool result = minijson_parse_value(input, main);

	if((int)(input->YYLIMIT - input->YYCURSOR) > 0)
	{
		parser_input_t check_input;
		memset(&check_input, 0, sizeof(check_input));
		check_input.YYCURSOR = input->YYCURSOR;
		check_input.YYLIMIT = input->YYLIMIT;
		result = minijson_check_string(input);
	}

	free(input);

	if(result == false)
	{
		if(main != NULL)
			minijson_delete(main);
		return NULL;
	}

	return main;
}

